#!/usr/bin/env bash

BRANCH_NAME="$1"
TAG_NAME="history/$BRANCH_NAME"

echo "tag: $TAG_NAME "

# check if that fails, cause there can be duplicates in tag or anything else
# we should not proceed with deleting branch then
ERR=$(git tag $TAG_NAME $BRANCH_NAME 2>&1 > /dev/null)

if [[ $ERR ]]
then
    echo "ERR is set"
    echo "$ERR"
else
    ERR=$(git branch -D $BRANCH_NAME 2>&1 > /dev/null)
    # silent
    if [[ $ERR ]]
    then
        echo "ERR is set"
        echo "$ERR"
    fi
fi

echo "finish"

